name: PlawrightSharp Checks

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: We shouldn't mention puppeteer
      run: |
        search_result=$(grep -r -i -n "puppeteer" $GITHUB_WORKSPACE/src)
        if [[ $search_result ]]; then
            echo "Puppeteer found! \n $search_result"
            exit 0
        else
            echo "What is a puppeteer?"
        fi
